# -*- coding: utf-8 -*-
"""
Table de curation du catalogue d'exercices TrackMyWeight.

Source des visuels et des données de référence : https://github.com/yuhonas/free-exercise-db
Licence : The Unlicense (domaine public).

Colonnes :
    slug      identifiant stable interne — NE JAMAIS MODIFIER pour un exercice
              déjà publié (clé unique en base, référencée par l'historique).
    src       id dans free-exercise-db (donne accès aux 2 images départ/fin).
    nom       libellé français affiché.
    primary   MuscleGroup principal.
    secondary MuscleGroups secondaires.
    mech      COMPOUND | ISOLATION
    force     PUSH | PULL | HINGE | SQUAT | CARRY | STATIC | ROTATION
    equip     clés d'équipement (voir EquipmentSeed.kt).
    cues      consigne technique courte, en français.
"""

# slug, src, nom, primary, secondary, mech, force, equip, cues
E = [
    # ─────────────────────────────── PECTORAUX ───────────────────────────────
    ("bench_press", "Barbell_Bench_Press_-_Medium_Grip", "Développé couché",
     "CHEST", ["TRICEPS", "SHOULDERS_FRONT"], "COMPOUND", "PUSH",
     ["barbell_olympic", "bench_flat", "plates_olympic"],
     "Omoplates serrées et basses, pieds ancrés au sol. Descends la barre au niveau des tétons, coudes à 45° du buste."),
    ("incline_bench_press", "Barbell_Incline_Bench_Press_-_Medium_Grip", "Développé incliné",
     "CHEST", ["SHOULDERS_FRONT", "TRICEPS"], "COMPOUND", "PUSH",
     ["barbell_olympic", "bench_incline", "plates_olympic"],
     "Banc à 30°, pas plus : au-delà l'épaule prend le travail à la place du haut des pectoraux."),
    ("decline_bench_press", "Decline_Barbell_Bench_Press", "Développé décliné",
     "CHEST", ["TRICEPS"], "COMPOUND", "PUSH",
     ["barbell_olympic", "bench_decline", "plates_olympic"],
     "Cible le bas des pectoraux. Fais-toi assurer : la sortie de barre est délicate en position déclinée."),
    ("db_bench_press", "Dumbbell_Bench_Press", "Développé couché haltères",
     "CHEST", ["TRICEPS", "SHOULDERS_FRONT"], "COMPOUND", "PUSH",
     ["dumbbells_fixed", "bench_flat"],
     "Amplitude plus grande qu'à la barre. Descends jusqu'à sentir l'étirement, sans forcer sur l'épaule."),
    ("db_incline_press", "Incline_Dumbbell_Press", "Développé incliné haltères",
     "CHEST", ["SHOULDERS_FRONT"], "COMPOUND", "PUSH",
     ["dumbbells_fixed", "bench_incline"],
     "Ne fais pas cogner les haltères en haut : garde 5 cm d'écart pour maintenir la tension."),
    ("db_decline_press", "Decline_Dumbbell_Bench_Press", "Développé décliné haltères",
     "CHEST", ["TRICEPS"], "COMPOUND", "PUSH",
     ["dumbbells_fixed", "bench_decline"],
     "Bas des pectoraux, avec moins de contrainte sur l'épaule que la version barre."),
    ("db_flye", "Dumbbell_Flyes", "Écarté haltères",
     "CHEST", [], "ISOLATION", "PUSH",
     ["dumbbells_fixed", "bench_flat"],
     "Coudes légèrement fléchis et figés. C'est un mouvement d'ouverture, pas un développé."),
    ("db_incline_flye", "Incline_Dumbbell_Flyes", "Écarté incliné haltères",
     "CHEST", ["SHOULDERS_FRONT"], "ISOLATION", "PUSH",
     ["dumbbells_fixed", "bench_incline"],
     "Étirement du haut des pectoraux. Charge légère, contrôle total en phase négative."),
    ("cable_flye", "Cable_Crossover", "Écarté poulies",
     "CHEST", [], "ISOLATION", "PUSH",
     ["cable_crossover"],
     "Tension constante sur toute l'amplitude. Croise légèrement les mains devant toi en fin de mouvement."),
    ("low_cable_flye", "Low_Cable_Crossover", "Écarté poulies basses",
     "CHEST", ["SHOULDERS_FRONT"], "ISOLATION", "PUSH",
     ["cable_crossover"],
     "Trajectoire de bas en haut : cible le haut des pectoraux. Termine mains à hauteur d'épaules."),
    ("pec_deck", "Butterfly", "Pec deck",
     "CHEST", [], "ISOLATION", "PUSH",
     ["pec_deck"],
     "Règle le siège pour que les poignées soient à hauteur de poitrine. Dos plaqué au dossier."),
    ("chest_press_machine", "Leverage_Chest_Press", "Machine développé pectoraux",
     "CHEST", ["TRICEPS", "SHOULDERS_FRONT"], "COMPOUND", "PUSH",
     ["chest_press_machine"],
     "Bonne option pour aller à l'échec en sécurité, sans assurage."),
    ("smith_bench_press", "Smith_Machine_Bench_Press", "Développé couché Smith",
     "CHEST", ["TRICEPS", "SHOULDERS_FRONT"], "COMPOUND", "PUSH",
     ["smith_machine", "bench_flat"],
     "Trajectoire guidée : utile pour charger lourd seul. Positionne bien le banc sous la barre."),
    ("dips_chest", "Dips_-_Chest_Version", "Dips (version pectoraux)",
     "CHEST", ["TRICEPS", "SHOULDERS_FRONT"], "COMPOUND", "PUSH",
     ["dip_bars"],
     "Buste penché en avant et coudes écartés pour cibler les pectoraux plutôt que les triceps."),
    ("pushup", "Pushups", "Pompes",
     "CHEST", ["TRICEPS", "SHOULDERS_FRONT"], "COMPOUND", "PUSH",
     [],
     "Corps gainé en ligne droite, des talons à la tête. Ne laisse pas les hanches s'affaisser."),
    ("pushup_feet_elevated", "Push-Ups_With_Feet_Elevated", "Pompes pieds surélevés",
     "CHEST", ["SHOULDERS_FRONT", "TRICEPS"], "COMPOUND", "PUSH",
     ["bench_flat"],
     "Plus les pieds sont hauts, plus le haut des pectoraux et les épaules travaillent."),
    ("trx_pushup", "Suspended_Push-Up", "Pompes en suspension",
     "CHEST", ["ABS", "TRICEPS"], "COMPOUND", "PUSH",
     ["trx"],
     "L'instabilité recrute fortement le gainage. Recule les pieds pour durcir l'exercice."),
    ("db_pullover", "Straight-Arm_Dumbbell_Pullover", "Pullover haltère",
     "CHEST", ["BACK_LATS", "TRICEPS"], "COMPOUND", "PULL",
     ["dumbbells_fixed", "bench_flat"],
     "Bras quasi tendus. Descends derrière la tête jusqu'à l'étirement, sans cambrer excessivement."),

    ("svend_press", "Svend_Press", "Svend press",
     "CHEST", [], "ISOLATION", "PUSH",
     ["plates_olympic"],
     "Deux disques pressés l'un contre l'autre devant la poitrine. Contraction pure, sans matériel lourd."),

    # ───────────────────────────────── DOS ────────────────────────────────────
    ("deadlift", "Barbell_Deadlift", "Soulevé de terre",
     "LOWER_BACK", ["HAMSTRINGS", "GLUTES", "TRAPS", "BACK_UPPER"], "COMPOUND", "HINGE",
     ["barbell_olympic", "plates_olympic"],
     "Barre contre les tibias, dos neutre, poitrine haute. Pousse le sol avec les jambes avant de tirer."),
    ("sumo_deadlift", "Sumo_Deadlift", "Soulevé de terre sumo",
     "LOWER_BACK", ["QUADS", "GLUTES", "HAMSTRINGS"], "COMPOUND", "HINGE",
     ["barbell_olympic", "plates_olympic"],
     "Appuis larges, mains à l'intérieur des jambes. Moins de contrainte lombaire que le conventionnel."),
    ("rack_pull", "Rack_Pulls", "Rack pull",
     "LOWER_BACK", ["TRAPS", "BACK_UPPER", "GLUTES"], "COMPOUND", "HINGE",
     ["barbell_olympic", "squat_rack", "plates_olympic"],
     "Soulevé de terre partiel depuis les barres de sécurité. Permet de charger plus lourd que le complet."),
    ("back_extension", "Hyperextensions_Back_Extensions", "Extension lombaires",
     "LOWER_BACK", ["GLUTES", "HAMSTRINGS"], "ISOLATION", "HINGE",
     ["back_extension"],
     "Monte jusqu'à l'alignement du buste avec les jambes, pas au-delà. Pas d'à-coups."),
    ("reverse_hyper", "Reverse_Hyperextension", "Extension lombaires inversée",
     "LOWER_BACK", ["GLUTES", "HAMSTRINGS"], "ISOLATION", "HINGE",
     ["back_extension"],
     "Le buste reste fixe, ce sont les jambes qui montent. Très doux pour le rachis."),
    ("pullup", "Pullups", "Traction",
     "BACK_LATS", ["BICEPS", "BACK_UPPER"], "COMPOUND", "PULL",
     ["pullup_bar"],
     "Amène la poitrine vers la barre, pas seulement le menton. Descends bras tendus à chaque rep."),
    ("chinup", "Chin-Up", "Chin-up (supination)",
     "BACK_LATS", ["BICEPS"], "COMPOUND", "PULL",
     ["pullup_bar"],
     "Prise en supination : les biceps participent davantage, tu seras plus fort qu'en traction classique."),
    ("weighted_pullup", "Weighted_Pull_Ups", "Traction lestée",
     "BACK_LATS", ["BICEPS", "BACK_UPPER"], "COMPOUND", "PULL",
     ["pullup_bar", "weight_belt"],
     "À partir de 12 tractions propres, ajoute du lest plutôt que des répétitions."),
    ("assisted_pullup_band", "Band_Assisted_Pull-Up", "Traction assistée élastique",
     "BACK_LATS", ["BICEPS"], "COMPOUND", "PULL",
     ["pullup_bar", "resistance_bands"],
     "L'élastique aide surtout en bas, là où c'est le plus dur. Réduis son épaisseur au fil des semaines."),
    ("lat_pulldown", "Wide-Grip_Lat_Pulldown", "Tirage vertical",
     "BACK_LATS", ["BICEPS", "BACK_UPPER"], "COMPOUND", "PULL",
     ["lat_pulldown"],
     "Amène la barre à la clavicule en gardant le buste presque vertical. Ne te balance pas."),
    ("close_grip_pulldown", "Close-Grip_Front_Lat_Pulldown", "Tirage vertical prise serrée",
     "BACK_LATS", ["BICEPS"], "COMPOUND", "PULL",
     ["lat_pulldown"],
     "Prise serrée neutre : plus d'amplitude et un travail marqué du bas des dorsaux."),
    ("underhand_pulldown", "Underhand_Cable_Pulldowns", "Tirage vertical supination",
     "BACK_LATS", ["BICEPS"], "COMPOUND", "PULL",
     ["lat_pulldown"],
     "Coudes le long du corps, tire vers le bas du sternum."),
    ("v_bar_pulldown", "V-Bar_Pulldown", "Tirage vertical poignée V",
     "BACK_LATS", ["BICEPS", "BACK_UPPER"], "COMPOUND", "PULL",
     ["lat_pulldown"],
     "Prise neutre, la plus confortable pour les épaules et les coudes."),
    ("straight_arm_pulldown", "Straight-Arm_Pulldown", "Pull-over poulie bras tendus",
     "BACK_LATS", [], "ISOLATION", "PULL",
     ["cable_column_single"],
     "Le seul isolant des dorsaux : bras tendus, seule l'épaule bouge. Parfait en pré-fatigue."),
    ("one_arm_pulldown", "One_Arm_Lat_Pulldown", "Tirage vertical unilatéral",
     "BACK_LATS", ["BICEPS"], "COMPOUND", "PULL",
     ["cable_column_single"],
     "Corrige les déséquilibres droite/gauche et augmente l'amplitude du dorsal."),
    ("v_bar_pullup", "V-Bar_Pullup", "Traction prise neutre",
     "BACK_LATS", ["BICEPS", "BACK_UPPER"], "COMPOUND", "PULL",
     ["pullup_bar"],
     "Prise neutre serrée : la plus confortable pour les épaules, et souvent la plus forte."),
    ("kneeling_high_pulley_row", "Kneeling_High_Pulley_Row", "Tirage poulie haute à genoux",
     "BACK_LATS", ["BACK_UPPER", "BICEPS"], "COMPOUND", "PULL",
     ["cable_column_single"],
     "À genoux face à la poulie haute. Tire vers le visage en écartant les coudes."),
    ("deficit_deadlift", "Deficit_Deadlift", "Soulevé de terre en déficit",
     "LOWER_BACK", ["HAMSTRINGS", "GLUTES", "QUADS"], "COMPOUND", "HINGE",
     ["barbell_olympic", "plates_olympic"],
     "Debout sur un disque : amplitude augmentée. Charge réduite, technique irréprochable exigée."),
    ("barbell_row", "Bent_Over_Barbell_Row", "Rowing barre",
     "BACK_UPPER", ["BACK_LATS", "BICEPS"], "COMPOUND", "PULL",
     ["barbell_olympic", "plates_olympic"],
     "Buste à 45°, dos neutre. Tire la barre vers le nombril, coudes près du corps."),
    ("reverse_grip_row", "Reverse_Grip_Bent-Over_Rows", "Rowing barre supination",
     "BACK_UPPER", ["BACK_LATS", "BICEPS"], "COMPOUND", "PULL",
     ["barbell_olympic", "plates_olympic"],
     "Prise en supination : recrute davantage le bas des dorsaux et les biceps."),
    ("db_row", "One-Arm_Dumbbell_Row", "Rowing haltère un bras",
     "BACK_LATS", ["BACK_UPPER", "BICEPS"], "COMPOUND", "PULL",
     ["dumbbells_fixed", "bench_flat"],
     "Un genou et une main sur le banc, dos à plat. Tire le coude vers la hanche."),
    ("db_row_two_arm", "Bent_Over_Two-Dumbbell_Row", "Rowing haltères deux bras",
     "BACK_UPPER", ["BACK_LATS", "BICEPS"], "COMPOUND", "PULL",
     ["dumbbells_fixed"],
     "Buste penché, gainage serré. Amplitude plus libre qu'à la barre."),
    ("seated_row", "Seated_Cable_Rows", "Tirage horizontal poulie",
     "BACK_UPPER", ["BACK_LATS", "BICEPS"], "COMPOUND", "PULL",
     ["seated_row"],
     "Buste fixe et vertical : ne te sers pas de l'élan du dos pour tirer la charge."),
    ("seated_row_one_arm", "Seated_One-arm_Cable_Pulley_Rows", "Tirage horizontal unilatéral",
     "BACK_UPPER", ["BACK_LATS", "BICEPS"], "COMPOUND", "PULL",
     ["cable_column_single"],
     "Laisse l'épaule s'avancer en phase basse pour maximiser l'étirement, puis tire."),
    ("t_bar_row", "T-Bar_Row_with_Handle", "Rowing T-Bar",
     "BACK_UPPER", ["BACK_LATS", "BICEPS"], "COMPOUND", "PULL",
     ["barbell_olympic", "plates_olympic"],
     "Permet de charger lourd avec moins de contrainte lombaire que le rowing barre."),
    ("smith_row", "Smith_Machine_Bent_Over_Row", "Rowing Smith machine",
     "BACK_UPPER", ["BACK_LATS", "BICEPS"], "COMPOUND", "PULL",
     ["smith_machine"],
     "Trajectoire guidée : tu peux te concentrer uniquement sur la contraction du dos."),
    ("kb_row", "One-Arm_Kettlebell_Row", "Rowing kettlebell",
     "BACK_UPPER", ["BACK_LATS", "BICEPS"], "COMPOUND", "PULL",
     ["kettlebells"],
     "Le centre de gravité décalé de la kettlebell sollicite davantage la prise et le gainage."),
    ("inverted_row", "Inverted_Row", "Rowing inversé",
     "BACK_UPPER", ["BACK_LATS", "BICEPS"], "COMPOUND", "PULL",
     ["barbell_olympic", "squat_rack"],
     "Corps gainé en planche. Plus la barre est basse, plus c'est difficile."),
    ("trx_row", "Suspended_Row", "Rowing en suspension",
     "BACK_UPPER", ["BACK_LATS", "BICEPS"], "COMPOUND", "PULL",
     ["trx"],
     "Ajuste la difficulté en avançant ou reculant les pieds. Serre les omoplates en haut."),
    ("incline_bench_pull", "Incline_Bench_Pull", "Rowing buste sur banc incliné",
     "BACK_UPPER", ["BACK_LATS", "BICEPS"], "COMPOUND", "PULL",
     ["dumbbells_fixed", "bench_incline"],
     "Poitrine calée sur le banc : supprime toute triche lombaire et isole le haut du dos."),

    # ─────────────────────────────── TRAPÈZES ────────────────────────────────
    ("shrug_barbell", "Barbell_Shrug", "Shrug barre",
     "TRAPS", [], "ISOLATION", "PULL",
     ["barbell_olympic", "plates_olympic"],
     "Monte les épaules droit vers les oreilles. Ne fais pas de rotation, ça n'apporte rien."),
    ("shrug_db", "Dumbbell_Shrug", "Shrug haltères",
     "TRAPS", [], "ISOLATION", "PULL",
     ["dumbbells_fixed"],
     "Marque une pause d'une seconde en haut, c'est là que le trapèze travaille vraiment."),
    ("shrug_cable", "Cable_Shrugs", "Shrug poulie",
     "TRAPS", [], "ISOLATION", "PULL",
     ["cable_column_single"],
     "Tension constante, y compris en bas du mouvement."),
    ("shrug_smith", "Smith_Machine_Behind_the_Back_Shrug", "Shrug Smith derrière le dos",
     "TRAPS", [], "ISOLATION", "PULL",
     ["smith_machine"],
     "Barre derrière les fesses : ouvre la poitrine et cible le milieu des trapèzes."),
    ("scapular_pullup", "Scapular_Pull-Up", "Traction scapulaire",
     "TRAPS", ["BACK_LATS"], "ISOLATION", "PULL",
     ["pullup_bar"],
     "Bras tendus, seules les omoplates bougent. Excellent échauffement avant les tractions."),
    ("upright_row", "Upright_Barbell_Row", "Rowing menton",
     "SHOULDERS_SIDE", ["TRAPS"], "COMPOUND", "PULL",
     ["barbell_ez"],
     "Ne monte pas les coudes au-dessus des épaules : au-delà, le risque de conflit est réel."),
    ("db_upright_row", "Standing_Dumbbell_Upright_Row", "Rowing menton haltères",
     "SHOULDERS_SIDE", ["TRAPS"], "COMPOUND", "PULL",
     ["dumbbells_fixed"],
     "Version haltères : trajectoire plus libre, plus tolérante pour l'épaule que la barre."),

    # ──────────────────────────────── ÉPAULES ────────────────────────────────
    ("ohp", "Standing_Military_Press", "Développé militaire barre",
     "SHOULDERS_FRONT", ["TRICEPS", "SHOULDERS_SIDE"], "COMPOUND", "PUSH",
     ["barbell_olympic", "plates_olympic"],
     "Fessiers et abdos serrés pour éviter de cambrer. Rentre la tête quand la barre passe le front."),
    ("seated_barbell_press", "Seated_Barbell_Military_Press", "Développé militaire assis",
     "SHOULDERS_FRONT", ["TRICEPS"], "COMPOUND", "PUSH",
     ["barbell_olympic", "bench_incline", "plates_olympic"],
     "Le dossier supprime la triche des jambes : plus strict que la version debout."),
    ("db_ohp", "Seated_Dumbbell_Press", "Développé haltères assis",
     "SHOULDERS_FRONT", ["TRICEPS", "SHOULDERS_SIDE"], "COMPOUND", "PUSH",
     ["dumbbells_fixed", "bench_incline"],
     "Coudes légèrement en avant du plan du corps, plus confortable pour l'épaule."),
    ("arnold_press", "Arnold_Dumbbell_Press", "Développé Arnold",
     "SHOULDERS_FRONT", ["SHOULDERS_SIDE", "TRICEPS"], "COMPOUND", "PUSH",
     ["dumbbells_fixed", "bench_incline"],
     "Rotation des paumes pendant la montée : recrute l'avant et le côté de l'épaule."),
    ("shoulder_press_machine", "Machine_Shoulder_Military_Press", "Machine développé épaules",
     "SHOULDERS_FRONT", ["TRICEPS"], "COMPOUND", "PUSH",
     ["shoulder_press_machine"],
     "Idéal pour finir les épaules en fin de séance sans risque de perte d'équilibre."),
    ("smith_ohp", "Smith_Machine_Overhead_Shoulder_Press", "Développé épaules Smith",
     "SHOULDERS_FRONT", ["TRICEPS"], "COMPOUND", "PUSH",
     ["smith_machine", "bench_incline"],
     "Assieds-toi de façon à ce que la barre descende devant le visage, jamais derrière la nuque."),
    ("kb_press", "Two-Arm_Kettlebell_Military_Press", "Développé militaire kettlebells",
     "SHOULDERS_FRONT", ["TRICEPS", "ABS"], "COMPOUND", "PUSH",
     ["kettlebells"],
     "Le poids qui repose sur l'avant-bras force un gainage et un placement d'épaule stricts."),
    ("front_raise", "Front_Dumbbell_Raise", "Élévations frontales",
     "SHOULDERS_FRONT", [], "ISOLATION", "PUSH",
     ["dumbbells_fixed"],
     "Monte jusqu'à hauteur d'épaules, pas plus haut. Charge légère, pas d'élan de hanches."),
    ("front_plate_raise", "Front_Plate_Raise", "Élévations frontales disque",
     "SHOULDERS_FRONT", [], "ISOLATION", "PUSH",
     ["plates_olympic"],
     "Tiens le disque à 3h et 9h. Amplitude jusqu'au niveau des yeux."),
    ("cable_front_raise", "Front_Cable_Raise", "Élévations frontales poulie",
     "SHOULDERS_FRONT", [], "ISOLATION", "PUSH",
     ["cable_column_single"],
     "La poulie maintient la tension en bas, contrairement aux haltères."),
    ("lateral_raise", "Side_Lateral_Raise", "Élévations latérales",
     "SHOULDERS_SIDE", [], "ISOLATION", "PUSH",
     ["dumbbells_fixed"],
     "Léger, propre, sans balancier. Mène le mouvement par les coudes, pas par les mains."),
    ("seated_lateral_raise", "Seated_Side_Lateral_Raise", "Élévations latérales assis",
     "SHOULDERS_SIDE", [], "ISOLATION", "PUSH",
     ["dumbbells_fixed", "bench_incline"],
     "Assis, impossible de tricher avec les jambes : la version la plus stricte."),
    ("cable_lateral_raise", "Cable_Seated_Lateral_Raise", "Élévations latérales poulie",
     "SHOULDERS_SIDE", [], "ISOLATION", "PUSH",
     ["cable_column_single"],
     "Tension constante sur toute l'amplitude, y compris bras le long du corps."),
    ("band_lateral_raise", "Lateral_Raise_-_With_Bands", "Élévations latérales élastique",
     "SHOULDERS_SIDE", [], "ISOLATION", "PUSH",
     ["resistance_bands"],
     "La résistance croît en fin de mouvement, là où le deltoïde est le plus fort."),
    ("rear_delt_flye", "Reverse_Flyes", "Écarté oiseau (postérieurs)",
     "SHOULDERS_REAR", ["BACK_UPPER"], "ISOLATION", "PULL",
     ["dumbbells_fixed"],
     "Buste penché à 90°, pouces vers le bas. Charge légère, la contraction prime."),
    ("bent_over_rear_delt_raise", "Seated_Bent-Over_Rear_Delt_Raise", "Oiseau assis buste penché",
     "SHOULDERS_REAR", ["BACK_UPPER"], "ISOLATION", "PULL",
     ["dumbbells_fixed", "bench_flat"],
     "Poitrine posée sur les cuisses : verrouille le buste et isole le deltoïde postérieur."),
    ("cable_rear_delt_fly", "Cable_Rear_Delt_Fly", "Écarté postérieur poulies",
     "SHOULDERS_REAR", ["BACK_UPPER"], "ISOLATION", "PULL",
     ["cable_crossover"],
     "Poulies croisées à hauteur d'épaules. Ouvre en gardant les bras quasi tendus."),
    ("reverse_pec_deck", "Reverse_Machine_Flyes", "Pec deck inversé",
     "SHOULDERS_REAR", ["BACK_UPPER"], "ISOLATION", "PULL",
     ["pec_deck"],
     "Assis face au dossier. Le plus simple pour cibler l'arrière d'épaule sans tricher."),
    ("face_pull", "Face_Pull", "Face pull",
     "SHOULDERS_REAR", ["BACK_UPPER", "TRAPS"], "ISOLATION", "PULL",
     ["cable_column_single"],
     "Poulie à hauteur de visage. Tire la corde vers le front en écartant les mains."),
    ("band_pull_apart", "Band_Pull_Apart", "Écarté élastique",
     "SHOULDERS_REAR", ["BACK_UPPER"], "ISOLATION", "PULL",
     ["resistance_bands"],
     "Parfait en échauffement d'épaules ou entre les séries de développé."),
    ("external_rotation_cable", "External_Rotation_with_Cable", "Rotation externe poulie",
     "SHOULDERS_REAR", [], "ISOLATION", "ROTATION",
     ["cable_column_single"],
     "Prévention de la coiffe des rotateurs. Coude collé au corps, charge très légère."),
    ("cuban_press", "Cuban_Press", "Cuban press",
     "SHOULDERS_REAR", ["SHOULDERS_SIDE", "TRAPS"], "COMPOUND", "ROTATION",
     ["dumbbells_fixed"],
     "Tirage menton, rotation externe, puis développé. Le meilleur échauffement d'épaules qui existe."),
    ("db_scaption", "Dumbbell_Scaption", "Élévations dans le plan de l'omoplate",
     "SHOULDERS_SIDE", ["SHOULDERS_FRONT"], "ISOLATION", "PUSH",
     ["dumbbells_fixed"],
     "Bras à 30° en avant du plan du corps : la trajectoire la plus saine pour l'épaule."),

    # ──────────────────────────────── BICEPS ─────────────────────────────────
    ("barbell_curl", "Barbell_Curl", "Curl barre",
     "BICEPS", ["FOREARMS"], "ISOLATION", "PULL",
     ["barbell_olympic", "plates_olympic"],
     "Coudes fixes le long du corps. Si le buste recule, la charge est trop lourde."),
    ("ez_curl", "EZ-Bar_Curl", "Curl barre EZ",
     "BICEPS", ["FOREARMS"], "ISOLATION", "PULL",
     ["barbell_ez"],
     "La barre coudée soulage les poignets par rapport à la barre droite."),
    ("db_curl", "Dumbbell_Bicep_Curl", "Curl haltères",
     "BICEPS", ["FOREARMS"], "ISOLATION", "PULL",
     ["dumbbells_fixed"],
     "Termine en supination complète : le biceps est aussi un supinateur."),
    ("seated_db_curl", "Seated_Dumbbell_Curl", "Curl haltères assis",
     "BICEPS", ["FOREARMS"], "ISOLATION", "PULL",
     ["dumbbells_fixed", "bench_flat"],
     "Assis, impossible de donner de l'élan avec les jambes."),
    ("incline_db_curl", "Incline_Dumbbell_Curl", "Curl incliné haltères",
     "BICEPS", [], "ISOLATION", "PULL",
     ["dumbbells_fixed", "bench_incline"],
     "Bras derrière le corps : étirement maximal de la longue portion du biceps."),
    ("hammer_curl", "Hammer_Curls", "Curl marteau",
     "BICEPS", ["FOREARMS"], "ISOLATION", "PULL",
     ["dumbbells_fixed"],
     "Prise neutre : cible le brachial, qui pousse le biceps vers le haut et épaissit le bras."),
    ("cable_hammer_curl", "Cable_Hammer_Curls_-_Rope_Attachment", "Curl marteau corde",
     "BICEPS", ["FOREARMS"], "ISOLATION", "PULL",
     ["cable_column_single"],
     "Écarte les extrémités de la corde en haut pour intensifier la contraction."),
    ("cross_body_hammer_curl", "Cross_Body_Hammer_Curl", "Curl marteau croisé",
     "BICEPS", ["FOREARMS"], "ISOLATION", "PULL",
     ["dumbbells_fixed"],
     "Amène l'haltère vers l'épaule opposée : accentue le travail du brachial."),
    ("preacher_curl", "Preacher_Curl", "Curl Larry Scott",
     "BICEPS", [], "ISOLATION", "PULL",
     ["barbell_ez", "preacher_bench"],
     "Aisselles calées sur le pupitre. Ne tends jamais complètement les coudes en bas."),
    ("machine_preacher_curl", "Machine_Preacher_Curls", "Curl pupitre machine",
     "BICEPS", [], "ISOLATION", "PULL",
     ["preacher_bench"],
     "Résistance guidée, parfait pour les séries dégressives en fin de séance."),
    ("cable_curl", "Standing_Biceps_Cable_Curl", "Curl poulie basse",
     "BICEPS", [], "ISOLATION", "PULL",
     ["cable_column_single"],
     "Tension constante du début à la fin, contrairement aux haltères."),
    ("concentration_curl", "Concentration_Curls", "Curl concentration",
     "BICEPS", [], "ISOLATION", "PULL",
     ["dumbbells_fixed", "bench_flat"],
     "Coude calé à l'intérieur de la cuisse. Le plus fort pic de contraction du biceps."),
    ("spider_curl", "Spider_Curl", "Spider curl",
     "BICEPS", [], "ISOLATION", "PULL",
     ["barbell_ez", "bench_incline"],
     "Buste posé sur un banc incliné, bras pendants : tension maximale en position haute."),
    ("drag_curl", "Drag_Curl", "Drag curl",
     "BICEPS", [], "ISOLATION", "PULL",
     ["barbell_ez"],
     "Fais glisser la barre le long du torse en reculant les coudes."),
    ("reverse_curl", "Reverse_Barbell_Curl", "Curl inversé (pronation)",
     "BICEPS", ["FOREARMS"], "ISOLATION", "PULL",
     ["barbell_ez"],
     "Prise en pronation : cible le brachio-radial. Charge nettement plus légère qu'en curl classique."),
    ("zottman_curl", "Zottman_Curl", "Curl Zottman",
     "BICEPS", ["FOREARMS"], "ISOLATION", "PULL",
     ["dumbbells_fixed"],
     "Monte en supination, tourne les poignets, descends en pronation. Biceps et avant-bras d'un coup."),

    # ──────────────────────────────── TRICEPS ────────────────────────────────
    ("close_grip_bench", "Close-Grip_Barbell_Bench_Press", "Développé prise serrée",
     "TRICEPS", ["CHEST", "SHOULDERS_FRONT"], "COMPOUND", "PUSH",
     ["barbell_olympic", "bench_flat", "plates_olympic"],
     "Mains à largeur d'épaules, pas plus serré : trop serré agresse les poignets."),
    ("close_grip_db_press", "Close-Grip_Dumbbell_Press", "Développé haltères serré",
     "TRICEPS", ["CHEST"], "COMPOUND", "PUSH",
     ["dumbbells_fixed", "bench_flat"],
     "Haltères collés l'un contre l'autre, coudes serrés le long du buste."),
    ("jm_press", "JM_Press", "JM press",
     "TRICEPS", ["CHEST"], "COMPOUND", "PUSH",
     ["barbell_olympic", "bench_flat", "plates_olympic"],
     "Hybride entre barre au front et développé serré. Très efficace pour la force de verrouillage."),
    ("dips_triceps", "Dips_-_Triceps_Version", "Dips triceps (buste droit)",
     "TRICEPS", ["CHEST"], "COMPOUND", "PUSH",
     ["dip_bars"],
     "Buste vertical et coudes serrés : c'est ce qui bascule le travail sur les triceps."),
    ("dip_machine", "Dip_Machine", "Machine à dips",
     "TRICEPS", ["CHEST"], "COMPOUND", "PUSH",
     ["assisted_pullup"],
     "Charge réglable : utile pour progresser vers les dips au poids du corps."),
    ("ring_dips", "Ring_Dips", "Dips aux anneaux",
     "TRICEPS", ["CHEST", "SHOULDERS_FRONT"], "COMPOUND", "PUSH",
     ["gymnastic_rings"],
     "L'instabilité des anneaux multiplie la difficulté. À réserver si tu maîtrises les dips classiques."),
    ("bench_dips", "Bench_Dips", "Dips sur banc",
     "TRICEPS", ["SHOULDERS_FRONT"], "COMPOUND", "PUSH",
     ["bench_flat"],
     "Ne descends pas trop bas : l'épaule en rotation interne extrême est vulnérable."),
    ("triceps_pushdown", "Triceps_Pushdown_-_Rope_Attachment", "Extension poulie corde",
     "TRICEPS", [], "ISOLATION", "PUSH",
     ["cable_column_single"],
     "Coudes collés au corps. Écarte les brins de la corde en fin d'extension."),
    ("v_bar_pushdown", "Triceps_Pushdown_-_V-Bar_Attachment", "Extension poulie barre V",
     "TRICEPS", [], "ISOLATION", "PUSH",
     ["cable_column_single"],
     "Barre rigide : permet de charger plus lourd que la corde."),
    ("reverse_pushdown", "Reverse_Grip_Triceps_Pushdown", "Extension poulie supination",
     "TRICEPS", [], "ISOLATION", "PUSH",
     ["cable_column_single"],
     "Prise en supination : cible la portion médiale du triceps, souvent négligée."),
    ("overhead_extension", "Standing_Dumbbell_Triceps_Extension", "Extension nuque haltère",
     "TRICEPS", [], "ISOLATION", "PUSH",
     ["dumbbells_fixed"],
     "Bras au-dessus de la tête : c'est la position qui étire le mieux la longue portion."),
    ("rope_overhead_extension", "Cable_Rope_Overhead_Triceps_Extension", "Extension nuque poulie corde",
     "TRICEPS", [], "ISOLATION", "PUSH",
     ["cable_column_single"],
     "Dos à la poulie, buste légèrement penché. Tension constante en position étirée."),
    ("skull_crusher", "EZ-Bar_Skullcrusher", "Barre au front",
     "TRICEPS", [], "ISOLATION", "PUSH",
     ["barbell_ez", "bench_flat"],
     "Descends la barre derrière le crâne plutôt que sur le front : meilleur étirement, coudes préservés."),
    ("lying_db_extension", "Lying_Dumbbell_Tricep_Extension", "Extension haltères allongé",
     "TRICEPS", [], "ISOLATION", "PUSH",
     ["dumbbells_fixed", "bench_flat"],
     "Version haltères : chaque bras travaille indépendamment, plus tolérant pour les coudes."),
    ("machine_triceps_extension", "Machine_Triceps_Extension", "Machine extension triceps",
     "TRICEPS", [], "ISOLATION", "PUSH",
     ["chest_press_machine"],
     "Trajectoire imposée : idéal pour aller à l'échec en fin de séance."),
    ("kickback", "Tricep_Dumbbell_Kickback", "Kickback haltère",
     "TRICEPS", [], "ISOLATION", "PUSH",
     ["dumbbells_fixed"],
     "Bras collé au buste et immobile. Charge légère, contraction complète en fin de course."),
    ("diamond_pushup", "Push-Ups_-_Close_Triceps_Position", "Pompes diamant",
     "TRICEPS", ["CHEST"], "COMPOUND", "PUSH",
     [],
     "Mains jointes sous la poitrine, coudes rasant le corps."),
    ("floor_press", "Floor_Press", "Développé au sol",
     "TRICEPS", ["CHEST", "SHOULDERS_FRONT"], "COMPOUND", "PUSH",
     ["barbell_olympic", "plates_olympic"],
     "Le sol limite la descente : épaule protégée et travail concentré sur le verrouillage."),
    ("tate_press", "Tate_Press", "Tate press",
     "TRICEPS", [], "ISOLATION", "PUSH",
     ["dumbbells_fixed", "bench_flat"],
     "Coudes écartés, haltères descendus vers la poitrine. Cible durement le triceps interne."),

    # ─────────────────────────────── AVANT-BRAS ──────────────────────────────
    ("wrist_curl", "Palms-Up_Barbell_Wrist_Curl_Over_A_Bench", "Curl poignets",
     "FOREARMS", [], "ISOLATION", "PULL",
     ["dumbbells_fixed", "bench_flat"],
     "Avant-bras posés sur le banc. Laisse la barre rouler jusqu'au bout des doigts, puis remonte."),
    ("reverse_wrist_curl", "Palms-Down_Dumbbell_Wrist_Curl_Over_A_Bench", "Curl poignets inversé",
     "FOREARMS", [], "ISOLATION", "PULL",
     ["dumbbells_fixed", "bench_flat"],
     "Paumes vers le bas : travaille les extenseurs, utile contre l'épicondylite."),
    ("cable_wrist_curl", "Cable_Wrist_Curl", "Curl poignets poulie",
     "FOREARMS", [], "ISOLATION", "PULL",
     ["cable_column_single"],
     "Tension continue, plus douce pour les articulations que la barre."),
    ("plate_pinch", "Plate_Pinch", "Pince disques",
     "FOREARMS", [], "ISOLATION", "CARRY",
     ["plates_olympic"],
     "Deux disques pincés entre pouce et doigts. Travaille la prise pincée, faiblesse classique."),
    ("wrist_roller", "Wrist_Roller", "Enrouleur de poignet",
     "FOREARMS", [], "ISOLATION", "STATIC",
     [],
     "Enroule la corde bras tendus devant toi. Brûlure garantie en deux allers-retours."),
    ("finger_curls", "Finger_Curls", "Curl des doigts",
     "FOREARMS", [], "ISOLATION", "PULL",
     ["barbell_olympic", "plates_olympic"],
     "Barre tenue derrière les cuisses, on la laisse rouler puis on referme les doigts. Prise de fer."),
    ("farmer_walk", "Farmers_Walk", "Farmer walk",
     "FOREARMS", ["TRAPS", "ABS"], "COMPOUND", "CARRY",
     ["dumbbells_fixed"],
     "Marche lourde, épaules basses et gainage serré. Prise, trapèzes et gainage d'un coup."),

    # ────────────────────────────── QUADRICEPS ───────────────────────────────
    ("back_squat", "Barbell_Full_Squat", "Squat barre (dos)",
     "QUADS", ["GLUTES", "LOWER_BACK", "HAMSTRINGS"], "COMPOUND", "SQUAT",
     ["barbell_olympic", "squat_rack", "plates_olympic"],
     "Descends au moins jusqu'à la parallèle. Genoux dans l'axe des pieds, poitrine haute."),
    ("front_squat", "Front_Barbell_Squat", "Squat frontal",
     "QUADS", ["GLUTES", "LOWER_BACK"], "COMPOUND", "SQUAT",
     ["barbell_olympic", "squat_rack", "plates_olympic"],
     "Coudes hauts pour garder la barre en place. Buste plus vertical qu'au squat classique."),
    ("box_squat", "Box_Squat", "Squat sur box",
     "QUADS", ["GLUTES", "HAMSTRINGS"], "COMPOUND", "SQUAT",
     ["barbell_olympic", "squat_rack", "plates_olympic", "bench_flat"],
     "Effleure le box sans t'y asseoir lourdement. Standardise la profondeur d'une série à l'autre."),
    ("wide_stance_squat", "Wide_Stance_Barbell_Squat", "Squat appuis larges",
     "QUADS", ["GLUTES", "HAMSTRINGS"], "COMPOUND", "SQUAT",
     ["barbell_olympic", "squat_rack", "plates_olympic"],
     "Pieds larges et pointes ouvertes : davantage de fessiers et d'adducteurs."),
    ("zercher_squat", "Zercher_Squats", "Squat Zercher",
     "QUADS", ["GLUTES", "ABS", "BACK_UPPER"], "COMPOUND", "SQUAT",
     ["barbell_olympic", "squat_rack", "plates_olympic"],
     "Barre dans le pli des coudes. Inconfortable mais redoutable pour le gainage."),
    ("smith_squat", "Smith_Machine_Squat", "Squat Smith machine",
     "QUADS", ["GLUTES"], "COMPOUND", "SQUAT",
     ["smith_machine"],
     "Avance les pieds pour accentuer les quadriceps. Guidage utile quand tu t'entraînes seul."),
    ("bodyweight_squat", "Bodyweight_Squat", "Squat poids du corps",
     "QUADS", ["GLUTES"], "COMPOUND", "SQUAT",
     [],
     "Échauffement idéal avant les séries lourdes, ou volume en fin de séance."),
    ("goblet_squat", "Goblet_Squat", "Goblet squat",
     "QUADS", ["GLUTES"], "COMPOUND", "SQUAT",
     ["dumbbells_fixed"],
     "Haltère tenu contre la poitrine. Le contrepoids t'aide à rester droit et à descendre bas."),
    ("leg_press", "Leg_Press", "Presse à cuisses",
     "QUADS", ["GLUTES", "HAMSTRINGS"], "COMPOUND", "SQUAT",
     ["leg_press"],
     "Ne décolle jamais le bas du dos du dossier en position basse."),
    ("narrow_leg_press", "Narrow_Stance_Leg_Press", "Presse pieds serrés",
     "QUADS", [], "COMPOUND", "SQUAT",
     ["leg_press"],
     "Pieds serrés et bas sur la plateforme : accentue le vaste externe."),
    ("hack_squat", "Hack_Squat", "Hack squat machine",
     "QUADS", ["GLUTES"], "COMPOUND", "SQUAT",
     ["hack_squat"],
     "Dos plaqué, pieds au milieu de la plateforme. Le plus efficace pour isoler les quadriceps."),
    ("sissy_squat", "Weighted_Sissy_Squat", "Sissy squat",
     "QUADS", [], "ISOLATION", "SQUAT",
     [],
     "Genoux qui avancent, buste en arrière. Étirement extrême du quadriceps : progresse doucement."),
    ("bulgarian_split_squat", "Split_Squat_with_Dumbbells", "Fente bulgare",
     "QUADS", ["GLUTES", "HAMSTRINGS"], "COMPOUND", "SQUAT",
     ["dumbbells_fixed", "bench_flat"],
     "Pied arrière surélevé. Recule le pied avant pour cibler les fessiers, avance-le pour les quadriceps."),
    ("trx_split_squat", "Suspended_Split_Squat", "Fente en suspension",
     "QUADS", ["GLUTES"], "COMPOUND", "SQUAT",
     ["trx"],
     "Pied arrière dans la sangle : l'instabilité impose un travail d'équilibre supplémentaire."),
    ("lunge", "Dumbbell_Lunges", "Fente avant",
     "QUADS", ["GLUTES", "HAMSTRINGS"], "COMPOUND", "SQUAT",
     ["dumbbells_fixed"],
     "Grand pas, genou arrière proche du sol. Buste droit tout du long."),
    ("barbell_lunge", "Barbell_Lunge", "Fente barre",
     "QUADS", ["GLUTES", "HAMSTRINGS"], "COMPOUND", "SQUAT",
     ["barbell_olympic", "squat_rack", "plates_olympic"],
     "Barre sur le dos : permet de charger lourd, mais demande un bon équilibre."),
    ("walking_lunge", "Barbell_Walking_Lunge", "Fente marchée",
     "QUADS", ["GLUTES", "HAMSTRINGS"], "COMPOUND", "SQUAT",
     ["barbell_olympic", "plates_olympic"],
     "Enchaîne les pas sans marquer d'arrêt. Très exigeant sur le plan cardio."),
    ("reverse_lunge", "Dumbbell_Rear_Lunge", "Fente arrière",
     "QUADS", ["GLUTES"], "COMPOUND", "SQUAT",
     ["dumbbells_fixed"],
     "Plus douce pour les genoux que la fente avant, à privilégier en cas de gêne."),
    ("step_up", "Dumbbell_Step_Ups", "Montée sur banc",
     "QUADS", ["GLUTES"], "COMPOUND", "SQUAT",
     ["dumbbells_fixed", "bench_flat"],
     "Pousse avec la jambe qui est sur le banc, ne prends pas d'élan avec celle du bas."),
    ("pistol_squat", "Kettlebell_Pistol_Squat", "Pistol squat",
     "QUADS", ["GLUTES", "ABS"], "COMPOUND", "SQUAT",
     ["kettlebells"],
     "Squat sur une jambe, contrepoids devant. Exige mobilité de cheville et gainage."),
    ("kb_thruster", "Kettlebell_Thruster", "Thruster kettlebell",
     "QUADS", ["GLUTES", "SHOULDERS_FRONT", "TRICEPS"], "COMPOUND", "SQUAT",
     ["kettlebells"],
     "Squat enchaîné à un développé, sans temps mort. Très cardio, à placer en fin de séance."),
    ("plie_squat", "Plie_Dumbbell_Squat", "Squat sumo haltère",
     "QUADS", ["GLUTES"], "COMPOUND", "SQUAT",
     ["dumbbells_fixed"],
     "Pieds très larges, pointes ouvertes à 45°. Adducteurs et fessiers très sollicités."),
    ("leg_extension", "Leg_Extensions", "Extension quadriceps",
     "QUADS", [], "ISOLATION", "SQUAT",
     ["leg_extension"],
     "Marque un temps d'arrêt en haut, jambes tendues. Contrôle la descente."),
    ("single_leg_extension", "Single-Leg_Leg_Extension", "Extension quadriceps unilatérale",
     "QUADS", [], "ISOLATION", "SQUAT",
     ["leg_extension"],
     "Une jambe à la fois : révèle et corrige les déséquilibres."),

    # ──────────────────────────── ISCHIOS / FESSIERS ─────────────────────────
    ("romanian_deadlift", "Romanian_Deadlift", "Soulevé roumain",
     "HAMSTRINGS", ["GLUTES", "LOWER_BACK"], "COMPOUND", "HINGE",
     ["barbell_olympic", "plates_olympic"],
     "Jambes quasi tendues, hanches qui reculent. La barre frôle les cuisses. Dos absolument neutre."),
    ("db_rdl", "Stiff-Legged_Dumbbell_Deadlift", "Soulevé roumain haltères",
     "HAMSTRINGS", ["GLUTES"], "COMPOUND", "HINGE",
     ["dumbbells_fixed"],
     "Descends jusqu'à l'étirement des ischios, pas plus bas. Le dos ne doit jamais s'arrondir."),
    ("stiff_leg_deadlift", "Stiff-Legged_Barbell_Deadlift", "Soulevé jambes tendues",
     "HAMSTRINGS", ["GLUTES", "LOWER_BACK"], "COMPOUND", "HINGE",
     ["barbell_olympic", "plates_olympic"],
     "Encore plus tendu que le roumain. Charge modérée, l'étirement fait le travail."),
    ("good_morning", "Good_Morning", "Good morning",
     "HAMSTRINGS", ["LOWER_BACK", "GLUTES"], "COMPOUND", "HINGE",
     ["barbell_olympic", "squat_rack", "plates_olympic"],
     "Barre sur le dos, bascule du buste vers l'avant. Commence très léger, la technique prime."),
    ("leg_curl", "Lying_Leg_Curls", "Leg curl allongé",
     "HAMSTRINGS", [], "ISOLATION", "HINGE",
     ["leg_curl"],
     "Hanches plaquées au banc. Ne décolle pas le bassin pour finir la répétition."),
    ("seated_leg_curl", "Seated_Leg_Curl", "Leg curl assis",
     "HAMSTRINGS", [], "ISOLATION", "HINGE",
     ["leg_curl"],
     "Hanches fléchies : les ischios travaillent en position étirée, ce qui les développe mieux."),
    ("standing_leg_curl", "Standing_Leg_Curl", "Leg curl debout",
     "HAMSTRINGS", [], "ISOLATION", "HINGE",
     ["leg_curl"],
     "Une jambe à la fois, pour corriger les asymétries."),
    ("glute_ham_raise", "Glute_Ham_Raise", "Glute ham raise",
     "HAMSTRINGS", ["GLUTES", "LOWER_BACK"], "COMPOUND", "HINGE",
     ["back_extension"],
     "Un des exercices les plus durs pour les ischios. Aide-toi des mains au début."),
    ("nordic_curl", "Natural_Glute_Ham_Raise", "Nordic curl",
     "HAMSTRINGS", ["GLUTES"], "ISOLATION", "HINGE",
     [],
     "Chevilles bloquées, descente freinée le plus lentement possible. Excellente prévention des claquages."),
    ("kb_swing", "One-Arm_Kettlebell_Swings", "Swing kettlebell",
     "HAMSTRINGS", ["GLUTES", "LOWER_BACK", "SHOULDERS_FRONT"], "COMPOUND", "HINGE",
     ["kettlebells"],
     "Mouvement de hanches explosif, pas un squat. Les bras ne font que suivre."),
    ("hip_thrust", "Barbell_Hip_Thrust", "Hip thrust barre",
     "GLUTES", ["HAMSTRINGS"], "COMPOUND", "HINGE",
     ["barbell_olympic", "bench_flat", "plates_olympic"],
     "Omoplates sur le banc, menton rentré. Serre les fessiers une seconde en position haute."),
    ("barbell_glute_bridge", "Barbell_Glute_Bridge", "Glute bridge barre",
     "GLUTES", ["HAMSTRINGS"], "COMPOUND", "HINGE",
     ["barbell_olympic", "plates_olympic"],
     "Version au sol du hip thrust : amplitude réduite mais montage bien plus rapide."),
    ("glute_bridge", "Butt_Lift_Bridge", "Glute bridge",
     "GLUTES", ["HAMSTRINGS"], "ISOLATION", "HINGE",
     [],
     "Au poids du corps. Pousse dans les talons et serre fort en haut."),
    ("single_leg_glute_bridge", "Single_Leg_Glute_Bridge", "Glute bridge unilatéral",
     "GLUTES", ["HAMSTRINGS"], "ISOLATION", "HINGE",
     [],
     "Une jambe tendue en l'air : double la charge sans matériel."),
    ("cable_kickback", "One-Legged_Cable_Kickback", "Kickback fessier poulie",
     "GLUTES", ["HAMSTRINGS"], "ISOLATION", "HINGE",
     ["cable_column_single"],
     "Sangle à la cheville. Extension de hanche contrôlée, sans cambrer le bas du dos."),
    ("glute_kickback", "Glute_Kickback", "Kickback fessier au sol",
     "GLUTES", [], "ISOLATION", "HINGE",
     [],
     "À quatre pattes. Monte le talon vers le plafond en gardant le bassin stable."),
    ("pull_through", "Pull_Through", "Pull through poulie",
     "GLUTES", ["HAMSTRINGS"], "COMPOUND", "HINGE",
     ["cable_column_single"],
     "Dos à la poulie, corde entre les jambes. Apprend le mouvement de charnière sans charge axiale."),
    ("kneeling_squat", "Kneeling_Squat", "Squat à genoux",
     "GLUTES", ["HAMSTRINGS"], "COMPOUND", "HINGE",
     ["barbell_olympic", "squat_rack", "plates_olympic"],
     "À genoux, barre sur le dos. Supprime les quadriceps et isole l'extension de hanche."),
    ("step_up_knee_raise", "Step-up_with_Knee_Raise", "Montée avec relevé de genou",
     "GLUTES", ["QUADS", "ABS"], "COMPOUND", "SQUAT",
     ["bench_flat"],
     "Montée puis relevé du genou opposé. Travail d'équilibre et de fessier moyen."),
    ("band_hip_abduction", "Monster_Walk", "Marche latérale élastique",
     "GLUTES", [], "ISOLATION", "STATIC",
     ["resistance_bands"],
     "Élastique au-dessus des genoux, demi-squat, pas latéraux. Réveille le moyen fessier."),

    # ──────────────────────────────── MOLLETS ────────────────────────────────
    ("standing_calf_raise", "Standing_Calf_Raises", "Mollets debout",
     "CALVES", [], "ISOLATION", "PUSH",
     ["calf_raise_machine"],
     "Amplitude complète : talon bien bas, puis extension maximale. Pause d'une seconde en haut."),
    ("barbell_calf_raise", "Standing_Barbell_Calf_Raise", "Mollets debout barre",
     "CALVES", [], "ISOLATION", "PUSH",
     ["barbell_olympic", "squat_rack", "plates_olympic"],
     "Avant-pieds sur une cale pour gagner en amplitude."),
    ("smith_calf_raise", "Smith_Machine_Calf_Raise", "Mollets Smith machine",
     "CALVES", [], "ISOLATION", "PUSH",
     ["smith_machine"],
     "Le guidage permet de se concentrer uniquement sur l'amplitude de cheville."),
    ("seated_calf_raise", "Seated_Calf_Raise", "Mollets assis",
     "CALVES", [], "ISOLATION", "PUSH",
     ["calf_raise_machine"],
     "Genoux fléchis : cible le soléaire, sous le jumeau. Indispensable pour épaissir le mollet."),
    ("donkey_calf_raise", "Donkey_Calf_Raises", "Mollets donkey",
     "CALVES", [], "ISOLATION", "PUSH",
     ["calf_raise_machine"],
     "Buste penché : place le jumeau en position étirée, la plus productive."),
    ("calf_press_leg_press", "Calf_Press_On_The_Leg_Press_Machine", "Mollets à la presse",
     "CALVES", [], "ISOLATION", "PUSH",
     ["leg_press"],
     "Avant-pieds en bas de la plateforme. Ne verrouille jamais les genoux."),
    ("db_calf_raise", "Standing_Dumbbell_Calf_Raise", "Mollets haltère (unilatéral)",
     "CALVES", [], "ISOLATION", "PUSH",
     ["dumbbells_fixed"],
     "Une jambe à la fois, en te tenant d'une main pour l'équilibre."),

    # ────────────────────────── ABDOMINAUX / OBLIQUES ────────────────────────
    ("plank", "Plank", "Planche",
     "ABS", ["OBLIQUES"], "ISOLATION", "STATIC",
     [],
     "Bassin en rétroversion, fessiers serrés. Mieux vaut 30 s parfaites que 2 min affaissées."),
    ("side_plank", "Side_Bridge", "Planche latérale",
     "OBLIQUES", ["ABS"], "ISOLATION", "STATIC",
     [],
     "Corps parfaitement aligné, hanche haute. Ne laisse pas le bassin descendre."),
    ("dead_bug", "Dead_Bug", "Dead bug",
     "ABS", [], "ISOLATION", "STATIC",
     [],
     "Bas du dos plaqué au sol en permanence. Si tu perds le contact, réduis l'amplitude."),
    ("crunch", "Crunches", "Crunch",
     "ABS", [], "ISOLATION", "STATIC",
     [],
     "Enroule la colonne vertèbre par vertèbre. Ne tire pas sur la nuque avec les mains."),
    ("weighted_crunch", "Weighted_Crunches", "Crunch lesté",
     "ABS", [], "ISOLATION", "STATIC",
     ["plates_olympic"],
     "Disque sur la poitrine. Les abdos répondent à la surcharge comme n'importe quel muscle."),
    ("decline_crunch", "Decline_Crunch", "Crunch décliné",
     "ABS", [], "ISOLATION", "STATIC",
     ["bench_decline"],
     "L'inclinaison augmente la résistance en début de mouvement."),
    ("sit_up", "Sit-Up", "Sit-up",
     "ABS", ["OBLIQUES"], "ISOLATION", "STATIC",
     [],
     "Amplitude complète jusqu'à la position assise. Plus sollicitant que le crunch pour les fléchisseurs."),
    ("cable_crunch", "Cable_Crunch", "Crunch poulie",
     "ABS", [], "ISOLATION", "STATIC",
     ["cable_column_single"],
     "À genoux, corde derrière la nuque. Enroule le buste, les hanches restent fixes."),
    ("ab_crunch_machine", "Ab_Crunch_Machine", "Machine abdominaux",
     "ABS", [], "ISOLATION", "STATIC",
     ["ab_crunch_machine"],
     "Charge progressive et trajectoire guidée : le plus simple pour surcharger les abdos."),
    ("reverse_crunch", "Reverse_Crunch", "Crunch inversé",
     "ABS", [], "ISOLATION", "STATIC",
     [],
     "Ce sont les hanches qui décollent, pas les épaules. Cible le bas des abdos."),
    ("lying_leg_raise", "Flat_Bench_Lying_Leg_Raise", "Relevé de jambes allongé",
     "ABS", [], "ISOLATION", "STATIC",
     ["bench_flat"],
     "Bas du dos plaqué au banc. Ne laisse pas les jambes tirer sur les lombaires."),
    ("hanging_leg_raise", "Hanging_Leg_Raise", "Relevé de jambes suspendu",
     "ABS", ["OBLIQUES"], "ISOLATION", "STATIC",
     ["pullup_bar"],
     "Sans balancement. Bascule le bassin vers le haut en fin de mouvement, sinon ce sont les hanches qui travaillent."),
    ("hanging_knee_raise", "Knee_Hip_Raise_On_Parallel_Bars", "Relevé de genoux aux barres",
     "ABS", ["OBLIQUES"], "ISOLATION", "STATIC",
     ["dip_bars"],
     "Version accessible du relevé de jambes tendues. Avant-bras calés, dos plaqué."),
    ("jackknife", "Jackknife_Sit-Up", "Jackknife",
     "ABS", [], "ISOLATION", "STATIC",
     [],
     "Bras et jambes se rejoignent au-dessus du bassin. Mouvement contrôlé, pas d'élan."),
    ("ab_wheel_rollout", "Ab_Roller", "Roue abdominale",
     "ABS", ["OBLIQUES"], "COMPOUND", "STATIC",
     ["ab_wheel"],
     "Commence à genoux. Ne cambre jamais : si le bas du dos creuse, arrête l'extension plus tôt."),
    ("trx_fallout", "Suspended_Fallout", "Fallout en suspension",
     "ABS", ["SHOULDERS_FRONT"], "COMPOUND", "STATIC",
     ["trx"],
     "Même principe que la roue, avec une difficulté réglable par l'inclinaison du corps."),
    ("turkish_getup", "Kettlebell_Turkish_Get-Up_Squat_style", "Turkish get-up",
     "ABS", ["SHOULDERS_FRONT", "GLUTES", "OBLIQUES"], "COMPOUND", "STATIC",
     ["kettlebells"],
     "Se relever du sol avec la kettlebell tendue au-dessus de la tête. Gainage, mobilité et stabilité d'épaule."),
    ("russian_twist", "Russian_Twist", "Russian twist",
     "OBLIQUES", ["ABS"], "ISOLATION", "ROTATION",
     [],
     "La rotation part du buste, pas des bras. Garde le dos droit, pas rond."),
    ("cable_russian_twist", "Cable_Russian_Twists", "Russian twist poulie",
     "OBLIQUES", ["ABS"], "ISOLATION", "ROTATION",
     ["cable_column_single"],
     "Bras tendus, rotation du tronc seul. Les hanches restent face à l'avant."),
    ("cable_woodchop", "Standing_Cable_Wood_Chop", "Bûcheron poulie",
     "OBLIQUES", ["ABS"], "COMPOUND", "ROTATION",
     ["cable_column_single"],
     "Mouvement diagonal de haut en bas. Pivote sur les pieds, ne force pas sur le rachis."),
    ("pallof_press", "Pallof_Press", "Pallof press",
     "OBLIQUES", ["ABS"], "ISOLATION", "STATIC",
     ["cable_column_single"],
     "Anti-rotation : le but est de ne pas tourner malgré la traction latérale. Très fonctionnel."),
    ("landmine_180", "Landmine_180s", "Landmine 180°",
     "OBLIQUES", ["ABS", "SHOULDERS_FRONT"], "COMPOUND", "ROTATION",
     ["barbell_olympic", "plates_olympic"],
     "Rotation d'un côté à l'autre, bras tendus. Pivote les pieds pour protéger les genoux."),
    ("db_side_bend", "Dumbbell_Side_Bend", "Flexion latérale haltère",
     "OBLIQUES", [], "ISOLATION", "STATIC",
     ["dumbbells_fixed"],
     "Un seul haltère, à charger modérément : trop lourd, ça épaissit la taille."),
    ("cross_body_crunch", "Cross-Body_Crunch", "Crunch croisé",
     "OBLIQUES", ["ABS"], "ISOLATION", "ROTATION",
     [],
     "Coude vers le genou opposé, en contractant l'oblique plutôt qu'en tirant sur la nuque."),
    ("oblique_crunch", "Oblique_Crunches", "Crunch oblique",
     "OBLIQUES", ["ABS"], "ISOLATION", "ROTATION",
     [],
     "Jambes basculées sur le côté, buste à plat. Isole bien l'oblique."),

    # ───────────────────────────────── NUQUE ─────────────────────────────────
    ("neck_isometric_front_back", "Isometric_Neck_Exercise_-_Front_And_Back", "Isométrie nuque avant/arrière",
     "NECK", [], "ISOLATION", "STATIC",
     [],
     "Résistance avec la main, sans mouvement. 10 s par direction, sans forcer."),
    ("neck_isometric_sides", "Isometric_Neck_Exercise_-_Sides", "Isométrie nuque latérale",
     "NECK", [], "ISOLATION", "STATIC",
     [],
     "Même principe sur les côtés. Utile contre les tensions cervicales du travail assis."),
    ("neck_plate_face_up", "Lying_Face_Up_Plate_Neck_Resistance", "Nuque disque face au ciel",
     "NECK", [], "ISOLATION", "STATIC",
     ["plates_olympic"],
     "Allongé sur le dos, disque léger sur le front avec une serviette. Amplitude courte et lente."),
]


# ─────────────────────────────────────────────────────────────────────────────
# Visuels d'équipement
# ─────────────────────────────────────────────────────────────────────────────
# Clé d'équipement (EquipmentSeed.kt) -> id free-exercise-db.
#
# Une seule image par équipement (pas d'animation) : il s'agit d'identifier une
# machine dans la salle, pas de démontrer un mouvement. Les images retenues
# montrent la machine avec quelqu'un dessus, ce qui lève l'ambiguïté bien mieux
# qu'une photo de matériel vide.
#
# Les accessoires sans visuel distinctif ne sont volontairement pas mappés
# (ceinture, sangles, foam roller, micro-poids, barres courtes, haltères
# réglables) : l'UI affiche alors simplement le nom.
EQUIPMENT_MEDIA = {
    "barbell_olympic": "Barbell_Full_Squat",
    "barbell_ez": "EZ-Bar_Curl",
    "plates_olympic": "Front_Plate_Raise",
    "dumbbells_fixed": "Dumbbell_Bicep_Curl",
    "kettlebells": "Two-Arm_Kettlebell_Military_Press",
    "bench_flat": "Dumbbell_Bench_Press",
    "bench_incline": "Incline_Dumbbell_Press",
    "bench_decline": "Decline_Barbell_Bench_Press",
    "squat_rack": "Barbell_Full_Squat",
    "smith_machine": "Smith_Machine_Bench_Press",
    "preacher_bench": "Preacher_Curl",
    "leg_press": "Leg_Press",
    "hack_squat": "Hack_Squat",
    "leg_curl": "Lying_Leg_Curls",
    "leg_extension": "Leg_Extensions",
    "calf_raise_machine": "Standing_Calf_Raises",
    "pec_deck": "Butterfly",
    "chest_press_machine": "Leverage_Chest_Press",
    "shoulder_press_machine": "Machine_Shoulder_Military_Press",
    "lat_pulldown": "Wide-Grip_Lat_Pulldown",
    "seated_row": "Seated_Cable_Rows",
    "cable_crossover": "Cable_Crossover",
    "cable_column_single": "Triceps_Pushdown_-_Rope_Attachment",
    "assisted_pullup": "Dip_Machine",
    "ab_crunch_machine": "Ab_Crunch_Machine",
    "back_extension": "Hyperextensions_Back_Extensions",
    "pullup_bar": "Pullups",
    "dip_bars": "Dips_-_Triceps_Version",
    "trx": "Suspended_Row",
    "gymnastic_rings": "Ring_Dips",
    "resistance_bands": "Band_Pull_Apart",
    "ab_wheel": "Ab_Roller",
    "treadmill": "Running_Treadmill",
    "stationary_bike": "Bicycling_Stationary",
    "rowing_machine": "Rowing_Stationary",
    "elliptical": "Elliptical_Trainer",
    "jump_rope": "Rope_Jumping",
    "stair_master": "Stairmaster",
}
